export {
  getDb,
  closeDb,
  getSyncStateValue,
  setSyncStateValue,
  deleteSyncStateValue,
  getStoryCount,
  listStories,
  getStoryByKey,
  getStoryCommits,
  searchStories,
  searchRefs,
  getStoryRefs,
  getStoryComments,
  getStoryHistory,
  listStoriesWithMetrics,
  getStoryChildren,
  replaceStoryCommits,
  getMigrationVersion,
  getStoryEnrichment,
  listStoryEnrichments,
  listEnrichmentsForStories,
  upsertStoryEnrichment,
  getConfluencePageCount,
  getCodeFileCount,
  getCodeFile,
  listReposIndexed,
  upsertCodeFile,
  deleteStaleCodeFiles,
  rebuildCodeSearchRow,
  searchCode,
  getPageById,
  listPages,
  upsertConfluencePage,
  replacePageAttachments,
  replacePageRefs,
  rebuildConfluenceSearchRow,
  retagWikiExtractedRefs,
  searchPages,
  searchGlobal,
  searchCodeStub,
  type ConfluencePageRow,
  type CodeFileRow,
  type CodeFileUpsertInput,
  type CodeSearchResultRow,
  type IndexedRepoRow,
  type ConfluencePageUpsertInput,
  type ConfluenceAttachmentUpsertInput,
  type PageRefUpsertInput,
  type PageSearchResultRow,
  type GlobalSearchHit,
  type GlobalSearchResult,
  type GlobalSearchSource,
  type CommitRow,
  type CommitUpsertInput,
  type EnrichmentRow,
  type EnrichmentType,
  type RefSearchRow,
  type SearchResultRow,
  type StoryFilters,
  type StoryHistoryRow,
  type StoryListRow,
  type Db,
} from './db.js';
export { runMigrations, ensureDataDir, CURRENT_MIGRATION_VERSION } from './migrate.js';
export { runSync, type SyncRunResult, type SyncRunOptions } from './pipeline.js';
export {
  runConfluenceSync,
  CONFLUENCE_BOOTSTRAP_COMPLETE_KEY,
  CONFLUENCE_BOOTSTRAP_CHECKPOINT_KEY,
  CONFLUENCE_LAST_SYNC_KEY,
  type ConfluenceSyncOptions,
  type ConfluenceSyncResult,
} from './confluence-sync.js';
export {
  runRepoSync,
  CODE_BOOTSTRAP_COMPLETE_KEY,
  CODE_BOOTSTRAP_CHECKPOINT_KEY,
  CODE_LAST_SYNC_KEY,
  type RepoSyncOptions,
  type RepoSyncResult,
} from './repo-sync.js';
export { enrichStoryCommits } from './vcs-enrich.js';
export {
  enrichStory,
  getStorySummary,
  queueStoryEnrichmentOnSync,
  SUPPORTED_ENRICHMENT_TYPES,
} from './enrichment.js';
export {
  extractSprintRefs,
  listStoriesForSprint,
  listBacklogStories,
  type SprintRef,
  type SprintStory,
} from './sprints.js';
